// Prasae Spectral Studio — browser-side Sentinel-2 visualization mixer.
// Uses quantized band PNGs generated by build_spectral_assets.py.
// These assets are for visualization only; verified statistics remain server-side float reflectance.

(() => {
  const VERSION = '20260818-2145';
  const BANDS = ['B02', 'B03', 'B04', 'B08', 'B11', 'B12'];
  const BAND_LABELS = {
    B02: 'B02 • Blue • 490 nm',
    B03: 'B03 • Green • 560 nm',
    B04: 'B04 • Red • 665 nm',
    B08: 'B08 • NIR • 842 nm',
    B11: 'B11 • SWIR1 • 1610 nm',
    B12: 'B12 • SWIR2 • 2190 nm'
  };
  const PRESETS = {
    truecolor: { label: 'True Color', r: 'B04', g: 'B03', b: 'B02', mode: 'rgb' },
    cir: { label: 'Color Infrared (CIR)', r: 'B08', g: 'B04', b: 'B03', mode: 'rgb' },
    swir: { label: 'SWIR Agriculture', r: 'B11', g: 'B08', b: 'B02', mode: 'rgb' },
    ndwi: { label: 'NDWI Water Index', mode: 'ndwi' }
  };

  let spectralMap = null;
  let spectralBaseLayer = null;
  let spectralOverlay = null;
  let spectralBoundary = null;
  let renderToken = 0;
  let currentPreset = 'truecolor';
  let selectedBands = { r: 'B04', g: 'B03', b: 'B02' };
  let brightness = 1.0;
  let contrast = 1.0;
  let gamma = 1.0;
  let overlayOpacity = 0.85;
  const manifestCache = new Map();
  const pixelCache = new Map();
  const renderCanvas = document.createElement('canvas');
  const renderCtx = renderCanvas.getContext('2d', { willReadFrequently: true });

  const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

  function injectStyles() {
    if (document.getElementById('spectral-studio-styles')) return;
    const style = document.createElement('style');
    style.id = 'spectral-studio-styles';
    style.textContent = `
      .spectral-studio-shell { display:grid; grid-template-columns:320px minmax(0,1fr); gap:14px; padding:16px; }
      .spectral-control-panel,
      .spectral-map-card {
        border:1px solid rgba(255,255,255,.08);
        background:rgba(15,23,42,.70);
        border-radius:12px;
        overflow:hidden;
      }
      .spectral-control-panel { padding:14px; align-self:start; }
      .spectral-section + .spectral-section { margin-top:14px; padding-top:14px; border-top:1px solid rgba(255,255,255,.07); }
      .spectral-title { font-size:.88rem; font-weight:800; color:#f8fafc; margin-bottom:4px; }
      .spectral-sub { color:#94a3b8; font-size:.67rem; line-height:1.45; }
      .spectral-preset-grid { display:grid; grid-template-columns:1fr 1fr; gap:7px; margin-top:9px; }
      .spectral-preset-btn {
        border:1px solid rgba(255,255,255,.10); background:#111827; color:#cbd5e1;
        border-radius:8px; padding:8px 7px; cursor:pointer; font-size:.68rem; font-weight:700;
      }
      .spectral-preset-btn:hover { border-color:rgba(56,189,248,.55); }
      .spectral-preset-btn.active { border-color:#38bdf8; background:rgba(56,189,248,.14); color:#e0f2fe; }
      .spectral-field { margin-top:9px; }
      .spectral-field label { display:block; color:#94a3b8; font-size:.62rem; font-weight:700; margin-bottom:4px; }
      .spectral-field select {
        width:100%; background:#0f172a; color:#e2e8f0; border:1px solid rgba(255,255,255,.10);
        border-radius:7px; padding:7px 8px; font-size:.68rem;
      }
      .spectral-slider-row { display:grid; grid-template-columns:72px minmax(0,1fr) 44px; gap:8px; align-items:center; margin-top:8px; }
      .spectral-slider-row label { color:#94a3b8; font-size:.61rem; }
      .spectral-slider-row input { width:100%; accent-color:#38bdf8; cursor:pointer; }
      .spectral-slider-value { color:#e2e8f0; font-size:.62rem; text-align:right; font-variant-numeric:tabular-nums; }
      .spectral-map-card { min-width:0; }
      .spectral-map-toolbar {
        display:flex; gap:10px; align-items:center; justify-content:space-between;
        padding:10px 12px; border-bottom:1px solid rgba(255,255,255,.07); flex-wrap:wrap;
      }
      .spectral-map-status { color:#cbd5e1; font-size:.68rem; line-height:1.4; }
      .spectral-map-status strong { color:#f8fafc; }
      .spectral-qa-pill {
        border:1px solid rgba(255,255,255,.10); border-radius:999px; padding:4px 8px;
        font-size:.61rem; color:#cbd5e1; background:rgba(15,23,42,.8);
      }
      #spectral-map { height:600px; min-height:440px; background:#0b1120; }
      .spectral-warning {
        margin-top:10px; padding:9px 10px; border-radius:8px;
        background:rgba(245,158,11,.08); border:1px solid rgba(245,158,11,.20);
        color:#fcd34d; font-size:.62rem; line-height:1.45;
      }
      .spectral-data-note { color:#64748b; font-size:.58rem; line-height:1.45; margin-top:8px; }
      .spectral-empty {
        position:absolute; inset:0; display:flex; align-items:center; justify-content:center;
        z-index:600; pointer-events:none; color:#cbd5e1; text-align:center; padding:20px;
        background:rgba(15,23,42,.30); font-size:.75rem;
      }
      .spectral-empty.hidden { display:none; }
      .spectral-map-wrap { position:relative; }
      @media(max-width:1050px) {
        .spectral-studio-shell { grid-template-columns:1fr; }
        #spectral-map { height:520px; }
      }
    `;
    document.head.appendChild(style);
  }

  function bandOptions(selected) {
    return BANDS.map(band => `<option value="${band}" ${band === selected ? 'selected' : ''}>${BAND_LABELS[band]}</option>`).join('');
  }

  function injectUI() {
    injectStyles();
    if (document.getElementById('wtab-spectral')) return;

    const tabs = document.querySelector('.workspace-tabs');
    const tableButton = document.getElementById('wtab-table');
    if (!tabs || !tableButton) return;

    const button = document.createElement('button');
    button.className = 'w-tab-btn';
    button.id = 'wtab-spectral';
    button.textContent = 'Spectral Studio';
    button.addEventListener('click', () => {
      switchWorkspaceTab('spectral');
      setTimeout(() => {
        ensureSpectralMap();
        spectralMap?.invalidateSize();
        refreshSpectralStudio();
      }, 120);
    });
    tabs.insertBefore(button, tableButton);

    const tablePanel = document.getElementById('panel-table');
    if (!tablePanel) return;
    const panel = document.createElement('div');
    panel.className = 'tab-content-panel';
    panel.id = 'panel-spectral';
    panel.innerHTML = `
      <div class="spectral-studio-shell">
        <aside class="spectral-control-panel">
          <div class="spectral-section">
            <div class="spectral-title">Satellite Spectral Studio</div>
            <div class="spectral-sub">ผสม Sentinel-2 bands ใน browser จาก band assets ของเดือนจริงเท่านั้น</div>
            <div class="spectral-field">
              <label for="spectral-date-select">Observation date</label>
              <select id="spectral-date-select"></select>
            </div>
            <div class="spectral-preset-grid">
              ${Object.entries(PRESETS).map(([key, preset]) => `<button class="spectral-preset-btn ${key === 'truecolor' ? 'active' : ''}" data-spectral-preset="${key}">${preset.label}</button>`).join('')}
            </div>
          </div>

          <div class="spectral-section" id="spectral-rgb-controls">
            <div class="spectral-title">Custom RGB Mixer</div>
            <div class="spectral-field"><label>Red channel</label><select id="spectral-r-band">${bandOptions('B04')}</select></div>
            <div class="spectral-field"><label>Green channel</label><select id="spectral-g-band">${bandOptions('B03')}</select></div>
            <div class="spectral-field"><label>Blue channel</label><select id="spectral-b-band">${bandOptions('B02')}</select></div>
          </div>

          <div class="spectral-section">
            <div class="spectral-title">Display tuning</div>
            <div class="spectral-slider-row"><label>Brightness</label><input id="spectral-brightness" type="range" min="50" max="200" value="100" step="1"><span class="spectral-slider-value" id="spectral-brightness-value">100%</span></div>
            <div class="spectral-slider-row"><label>Contrast</label><input id="spectral-contrast" type="range" min="50" max="200" value="100" step="1"><span class="spectral-slider-value" id="spectral-contrast-value">100%</span></div>
            <div class="spectral-slider-row"><label>Gamma</label><input id="spectral-gamma" type="range" min="50" max="250" value="100" step="1"><span class="spectral-slider-value" id="spectral-gamma-value">1.00</span></div>
            <div class="spectral-slider-row"><label>Opacity</label><input id="spectral-opacity" type="range" min="0" max="100" value="85" step="1"><span class="spectral-slider-value" id="spectral-opacity-value">85%</span></div>
          </div>

          <div class="spectral-warning">Visualization only — band PNG เป็น 8-bit fixed-scale เพื่อการแสดงผล ไม่ใช้แทน reflectance float สำหรับค่าสถิติ NDVI/Green Cover/NDRE</div>
          <div class="spectral-data-note">ไม่มี nearest-date fallback: ถ้า observation นั้นไม่มีข้อมูลที่ผ่าน QA ระบบจะแสดง Esri basemap และระบุ No spectral data</div>
        </aside>

        <section class="spectral-map-card">
          <div class="spectral-map-toolbar">
            <div class="spectral-map-status" id="spectral-status"><strong>Spectral Studio</strong> • กำลังโหลด</div>
            <span class="spectral-qa-pill" id="spectral-qa-pill">—</span>
          </div>
          <div class="spectral-map-wrap">
            <div id="spectral-map"></div>
            <div id="spectral-empty" class="spectral-empty hidden"></div>
          </div>
        </section>
      </div>`;
    tablePanel.parentNode.insertBefore(panel, tablePanel);

    const dateSelect = document.getElementById('spectral-date-select');
    MILESTONE_MONTHS.forEach((monthKey, index) => {
      const parsed = parseMonthKey(monthKey);
      const option = document.createElement('option');
      option.value = String(index);
      option.textContent = `${thaiMonths[parsed.month_num]} ${parsed.year}`;
      dateSelect.appendChild(option);
    });
    dateSelect.value = String(currentMonthIndex);
    dateSelect.addEventListener('change', event => setMonthIndex(Number(event.target.value)));

    document.querySelectorAll('[data-spectral-preset]').forEach(presetButton => {
      presetButton.addEventListener('click', () => applyPreset(presetButton.dataset.spectralPreset));
    });

    ['r', 'g', 'b'].forEach(channel => {
      document.getElementById(`spectral-${channel}-band`).addEventListener('change', event => {
        selectedBands[channel] = event.target.value;
        currentPreset = 'custom';
        updatePresetButtons();
        scheduleRender();
      });
    });

    document.getElementById('spectral-brightness').addEventListener('input', event => {
      brightness = Number(event.target.value) / 100;
      document.getElementById('spectral-brightness-value').textContent = `${event.target.value}%`;
      scheduleRender();
    });
    document.getElementById('spectral-contrast').addEventListener('input', event => {
      contrast = Number(event.target.value) / 100;
      document.getElementById('spectral-contrast-value').textContent = `${event.target.value}%`;
      scheduleRender();
    });
    document.getElementById('spectral-gamma').addEventListener('input', event => {
      gamma = Number(event.target.value) / 100;
      document.getElementById('spectral-gamma-value').textContent = gamma.toFixed(2);
      scheduleRender();
    });
    document.getElementById('spectral-opacity').addEventListener('input', event => {
      overlayOpacity = Number(event.target.value) / 100;
      document.getElementById('spectral-opacity-value').textContent = `${event.target.value}%`;
      spectralOverlay?.setOpacity(overlayOpacity);
    });
  }

  function ensureSpectralMap() {
    if (spectralMap || !document.getElementById('spectral-map')) return;
    spectralMap = L.map('spectral-map', { zoomControl: true, attributionControl: true }).setView([12.75, 101.80], 15);
    spectralBaseLayer = L.tileLayer(ESRI_WORLD_IMAGERY, { maxZoom: 19, attribution: 'Tiles &copy; Esri' }).addTo(spectralMap);
  }

  function updatePresetButtons() {
    document.querySelectorAll('[data-spectral-preset]').forEach(button => {
      button.classList.toggle('active', button.dataset.spectralPreset === currentPreset);
    });
  }

  function applyPreset(key) {
    const preset = PRESETS[key];
    if (!preset) return;
    currentPreset = key;
    if (preset.mode === 'rgb') {
      selectedBands = { r: preset.r, g: preset.g, b: preset.b };
      document.getElementById('spectral-r-band').value = preset.r;
      document.getElementById('spectral-g-band').value = preset.g;
      document.getElementById('spectral-b-band').value = preset.b;
    }
    document.getElementById('spectral-rgb-controls').style.opacity = preset.mode === 'ndwi' ? '.45' : '1';
    updatePresetButtons();
    scheduleRender();
  }

  async function loadManifest(plotId) {
    if (manifestCache.has(plotId)) return manifestCache.get(plotId);
    try {
      const response = await fetch(`data/plots/${plotId}/spectral_manifest.json?v=${VERSION}`, { cache: 'no-store' });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const manifest = await response.json();
      manifestCache.set(plotId, manifest);
      return manifest;
    } catch (error) {
      manifestCache.set(plotId, null);
      return null;
    }
  }

  async function loadBandPixels(plotId, monthKey, band) {
    const cacheKey = `${plotId}:${monthKey}:${band}`;
    if (pixelCache.has(cacheKey)) return pixelCache.get(cacheKey);
    const resultPromise = new Promise((resolve, reject) => {
      const image = new Image();
      image.onload = () => {
        try {
          const canvas = document.createElement('canvas');
          canvas.width = image.naturalWidth;
          canvas.height = image.naturalHeight;
          const ctx = canvas.getContext('2d', { willReadFrequently: true });
          ctx.drawImage(image, 0, 0);
          resolve(ctx.getImageData(0, 0, canvas.width, canvas.height));
        } catch (error) {
          reject(error);
        }
      };
      image.onerror = () => reject(new Error(`Missing ${band} ${monthKey}`));
      image.src = `data/plots/${plotId}/band_${band}_${monthKey}.png?v=${VERSION}`;
    });
    pixelCache.set(cacheKey, resultPromise);
    try {
      return await resultPromise;
    } catch (error) {
      pixelCache.delete(cacheKey);
      throw error;
    }
  }

  function tuneChannel(value) {
    let normalized = value / 255;
    normalized = (normalized - 0.5) * contrast + 0.5;
    normalized = clamp(normalized * brightness, 0, 1);
    normalized = Math.pow(normalized, 1 / Math.max(0.05, gamma));
    return Math.round(clamp(normalized, 0, 1) * 255);
  }

  function ndwiColor(value) {
    const v = clamp(value, -1, 1);
    if (v >= 0) {
      const t = v;
      return [Math.round(210 * (1 - t)), Math.round(235 * (1 - t) + 135 * t), 255];
    }
    const t = -v;
    return [Math.round(235 * (1 - t) + 120 * t), Math.round(230 * (1 - t) + 105 * t), Math.round(190 * (1 - t) + 70 * t)];
  }

  async function renderRgb(plotId, monthKey) {
    const [rData, gData, bData] = await Promise.all([
      loadBandPixels(plotId, monthKey, selectedBands.r),
      loadBandPixels(plotId, monthKey, selectedBands.g),
      loadBandPixels(plotId, monthKey, selectedBands.b)
    ]);
    const width = rData.width;
    const height = rData.height;
    if (gData.width !== width || bData.width !== width || gData.height !== height || bData.height !== height) {
      throw new Error('Band dimensions do not match');
    }
    renderCanvas.width = width;
    renderCanvas.height = height;
    const output = renderCtx.createImageData(width, height);
    for (let i = 0; i < output.data.length; i += 4) {
      output.data[i] = tuneChannel(rData.data[i]);
      output.data[i + 1] = tuneChannel(gData.data[i]);
      output.data[i + 2] = tuneChannel(bData.data[i]);
      output.data[i + 3] = Math.min(rData.data[i + 3], gData.data[i + 3], bData.data[i + 3]);
    }
    renderCtx.putImageData(output, 0, 0);
    return renderCanvas.toDataURL('image/png');
  }

  async function renderNdwi(plotId, monthKey) {
    const [green, nir] = await Promise.all([
      loadBandPixels(plotId, monthKey, 'B03'),
      loadBandPixels(plotId, monthKey, 'B08')
    ]);
    renderCanvas.width = green.width;
    renderCanvas.height = green.height;
    const output = renderCtx.createImageData(green.width, green.height);
    for (let i = 0; i < output.data.length; i += 4) {
      const g = green.data[i];
      const n = nir.data[i];
      const denom = g + n;
      const ndwi = denom > 0 ? (g - n) / denom : 0;
      const [r, gg, b] = ndwiColor(ndwi);
      output.data[i] = tuneChannel(r);
      output.data[i + 1] = tuneChannel(gg);
      output.data[i + 2] = tuneChannel(b);
      output.data[i + 3] = Math.min(green.data[i + 3], nir.data[i + 3]);
    }
    renderCtx.putImageData(output, 0, 0);
    return renderCanvas.toDataURL('image/png');
  }

  function setEmpty(message) {
    const el = document.getElementById('spectral-empty');
    if (!el) return;
    el.textContent = message || '';
    el.classList.toggle('hidden', !message);
  }

  function updateBoundary(plot) {
    if (!spectralMap || !plot?.geometry) return;
    if (spectralBoundary && spectralMap.hasLayer(spectralBoundary)) spectralMap.removeLayer(spectralBoundary);
    spectralBoundary = L.geoJSON({ type: 'Feature', properties: {}, geometry: plot.geometry }, {
      style: { color: '#34d399', weight: 2, opacity: 1, fillOpacity: 0 }
    }).addTo(spectralMap);
    const bounds = spectralBoundary.getBounds();
    if (bounds.isValid()) spectralMap.fitBounds(bounds, { padding: [42, 42], maxZoom: 17, animate: false });
    spectralBoundary.bringToFront();
  }

  function scheduleRender() {
    const token = ++renderToken;
    requestAnimationFrame(() => {
      if (token === renderToken) renderSpectralView(token);
    });
  }

  async function renderSpectralView(token = ++renderToken) {
    if (!activePlot) return;
    ensureSpectralMap();
    if (!spectralMap) return;

    const monthKey = MILESTONE_MONTHS[currentMonthIndex];
    const dateSelect = document.getElementById('spectral-date-select');
    if (dateSelect) dateSelect.value = String(currentMonthIndex);
    updateBoundary(activePlot);

    const status = document.getElementById('spectral-status');
    const qaPill = document.getElementById('spectral-qa-pill');
    if (status) status.innerHTML = `<strong>${escapeHtml(activePlot.name)}</strong> • ${monthKey} • loading spectral assets`;
    if (qaPill) qaPill.textContent = 'Loading…';
    setEmpty('กำลังโหลด Sentinel-2 spectral bands…');

    const manifest = await loadManifest(activePlot.id);
    if (token !== renderToken) return;
    if (!manifest) {
      if (spectralOverlay && spectralMap.hasLayer(spectralOverlay)) spectralMap.removeLayer(spectralOverlay);
      spectralOverlay = null;
      if (status) status.innerHTML = `<strong>${escapeHtml(activePlot.name)}</strong> • ยังไม่มี Spectral Studio assets สำหรับแปลงนี้`;
      if (qaPill) qaPill.textContent = 'Assets pending';
      setEmpty('ยังไม่มี B02/B03/B04/B08/B11/B12 assets สำหรับแปลงนี้\nEsri World Imagery ยังแสดงเป็นพื้นหลัง');
      return;
    }

    const dateRecord = (manifest.dates || []).find(item => item.month === monthKey);
    if (!dateRecord || !['observed_single_scene', 'observed_monthly_composite'].includes(dateRecord.status)) {
      if (spectralOverlay && spectralMap.hasLayer(spectralOverlay)) spectralMap.removeLayer(spectralOverlay);
      spectralOverlay = null;
      if (status) status.innerHTML = `<strong>${escapeHtml(activePlot.name)}</strong> • ${monthKey} • no spectral data`;
      if (qaPill) qaPill.textContent = dateRecord?.status || 'no_data';
      setEmpty(`ไม่มี spectral observation ที่ผ่าน QA สำหรับ ${monthKey}\nไม่มีการยืมภาพจากเดือนอื่น`);
      return;
    }

    try {
      const imageUrl = currentPreset === 'ndwi'
        ? await renderNdwi(activePlot.id, monthKey)
        : await renderRgb(activePlot.id, monthKey);
      if (token !== renderToken) return;

      const bounds = imageBoundsForPlot(activePlot);
      if (!spectralOverlay) {
        spectralOverlay = L.imageOverlay(imageUrl, bounds, { opacity: overlayOpacity, interactive: false }).addTo(spectralMap);
      } else {
        spectralOverlay.setBounds(bounds);
        spectralOverlay.setUrl(imageUrl);
        spectralOverlay.setOpacity(overlayOpacity);
        if (!spectralMap.hasLayer(spectralOverlay)) spectralOverlay.addTo(spectralMap);
      }
      spectralBoundary?.bringToFront();
      const modeLabel = currentPreset === 'ndwi'
        ? 'NDWI = (B03 - B08) / (B03 + B08)'
        : `${selectedBands.r} / ${selectedBands.g} / ${selectedBands.b}`;
      if (status) status.innerHTML = `<strong>${escapeHtml(activePlot.name)}</strong> • ${monthKey} • ${modeLabel}`;
      if (qaPill) qaPill.textContent = `${dateRecord.scenes_used} scene(s) • clear ${Number(dateRecord.clear_pixel_pct).toFixed(0)}%`;
      setEmpty('');
    } catch (error) {
      console.warn('Spectral Studio render failed:', error);
      if (status) status.innerHTML = `<strong>${escapeHtml(activePlot.name)}</strong> • ${monthKey} • render error`;
      if (qaPill) qaPill.textContent = 'Asset error';
      setEmpty('โหลด band assets ไม่ครบสำหรับ observation นี้');
    }
  }

  function refreshSpectralStudio() {
    if (!document.getElementById('panel-spectral')?.classList.contains('active')) return;
    const dateSelect = document.getElementById('spectral-date-select');
    if (dateSelect) dateSelect.value = String(currentMonthIndex);
    scheduleRender();
  }

  document.addEventListener('DOMContentLoaded', () => {
    injectUI();
    ensureSpectralMap();

    const observer = new MutationObserver(() => refreshSpectralStudio());
    ['kpi-current-plot-name', 'playback-date-display'].forEach(id => {
      const node = document.getElementById(id);
      if (node) observer.observe(node, { childList: true, characterData: true, subtree: true });
    });
  });
})();
